name: Test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Test
        run: go test -v -race -timeout 20m -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
